/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.mdd6b.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.mdd6b.TurtlesRuntimeModule;
import uk.ac.kcl.inf.mdd6b.TurtlesStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TurtlesIdeSetup extends TurtlesStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TurtlesRuntimeModule(), new TurtlesIdeModule()));
	}
	
}
